name: CI of mc_rtc

on:
  push:
    paths-ignore:
      # Changes to those files don't mandate running CI
      - ".gitlab-ci.yml"
      - ".jrl-ci"
      - ".github/workflows/package.yml"
      - "debian/**"
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  clang-format:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install clang-format-6.0
      run: |
        sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get -qq update
        sudo apt-get -qq remove clang-6.0 libclang1-6.0 libclang-common-6.0-dev libllvm6.0
        sudo apt-get -qq install clang-format-6.0 clang-format
    - name: Run clang-format-check
      run: |
        ./.clang-format-check.sh
  build:
    needs: clang-format
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest, windows-latest]
        build-type: [Debug, RelWithDebInfo]
        compiler: [gcc, clang]
        exclude:
          # Only default compiler on macos-latest and windows-latest
          - os: macos-latest
            compiler: clang
          - os: windows-latest
            compiler: clang
          # FIXME Getting strange linking errors on Xenial with clang
          - os: ubuntu-16.04
            compiler: clang

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Temporary APT mirrors cleanup
      run: |
        sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
      if: startsWith(runner.os, 'Linux')
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: cython cython3 python-nose python3-nose python-numpy python3-numpy python-coverage python3-coverage python-setuptools python3-setuptools libeigen3-dev doxygen doxygen-latex libboost-all-dev libtinyxml2-dev libgeos++-dev libnanomsg-dev libyaml-cpp-dev libltdl-dev
        macos: |
          cask: gfortran
          brew: eigen boost tinyxml2 geos nanomsg yaml-cpp pkg-config libtool
          pip: Cython coverage nose numpy
        windows: |
          pip: Cython coverage nose numpy
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7
            - path: leethomason/tinyxml2
              ref: 7.1.0
            - path: libgeos/geos
              ref: 3.6.3
            - path: nanomsg/nanomsg
              ref: 1.1.5
            - path: jbeder/yaml-cpp
        github: |
          - path: humanoid-path-planner/hpp-spline
            ref: v4.7.0
            options: -DBUILD_PYTHON_INTERFACE:BOOL=OFF
          - path: jrl-umi3218/Eigen3ToPython
          - path: jrl-umi3218/SpaceVecAlg
          - path: jrl-umi3218/sch-core
          - path: jrl-umi3218/eigen-qld
          - path: jrl-umi3218/sch-core-python
          - path: jrl-umi3218/RBDyn
          - path: jrl-umi3218/Tasks
          - path: jrl-umi3218/mc_rbdyn_urdf
          - path: jrl-umi3218/mc_rtc_data
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
    # FIXME Add a step to test ROS plugin on Ubuntu
    - name: Upload documentation
      # Only run on master branch and for one configuration
      if: matrix.os == 'ubuntu-18.04' && matrix.build-type == 'RelWithDebInfo' && matrix.compiler == 'gcc' && github.ref == 'refs/heads/master'
      uses: jrl-umi3218/github-actions/upload-documentation@master
      with:
        GH_USER: gergondet
        GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
    - name: Slack Notification
      if: failure()
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: '#ci'
        slack-text: >
          [mc_rtc] Build *${{ matrix.os }}/${{ matrix.build-type }} (${{ matrix.compiler }})* failed on ${{ github.ref }}
